---
composes:

  fedora_41:
    compose: Fedora-41

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-41-20251215.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-41-20251215.0

  fedora_41_image_mode:
    compose: Fedora-41-image-mode

    x86_64:
      image: Fedora-41-image-mode-x86_64

  fedora_42:
    compose: Fedora-42

    x86_64: &fedora_latest_ref_x86_64
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-42-20251228.0
    aarch64: &fedora_latest_ref_aarch64
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-42-20251228.0

  fedora_42_image_mode:
    compose: Fedora-42-image-mode

    x86_64: &fedora_latest_image_mode_ref_x86_64
      image: Fedora-42-image-mode-x86_64

  fedora_43:
    compose: Fedora-43

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-43-Prerelease-20251024.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-43-Prerelease-20251024.0

  fedora_43_image_mode:
    compose: Fedora-43-image-mode

    x86_64:
      image: Fedora-43-image-mode-x86_64

  # TFT-1221
  fedora_latest:
    compose: Fedora-latest

    x86_64: *fedora_latest_ref_x86_64
    aarch64: *fedora_latest_ref_aarch64

  fedora_latest_image_mode:
    compose: Fedora-latest-image-mode

    x86_64: *fedora_latest_image_mode_ref_x86_64

  fedora_rawhide:
    compose: Fedora-Rawhide

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-Rawhide-20251228.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-Rawhide-20251228.0

  fedora_rawhide_image_mode:
    compose: Fedora-Rawhide-image-mode

    x86_64:
      image: Fedora-Rawhide-image-mode-x86_64

  fedora_eln:
    compose: Fedora-eln

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-ELN-20251229.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-ELN-20251229.0

  centos_7:
    compose: CentOS-7

    x86_64:
      image: CentOS Linux 7 x86_64 - 2211
    aarch64:
      image: CentOS Linux 7 aarch64 - 2211

  centos_stream_8:
    compose: CentOS-Stream-8

    x86_64:
      image: CentOS Stream 8 x86_64
    aarch64:
      image: CentOS Stream 8 aarch64

  centos_stream_9:
    compose: CentOS-Stream-9

    x86_64:
      image: CentOS Stream 9 x86_64 20250825
    aarch64:
      image: CentOS Stream 9 aarch64 20250825

  centos_stream_9_image_mode:
    compose: CentOS-Stream-9-image-mode

    x86_64:
      image: CentOS-Stream-9-image-mode-x86_64

  centos_stream_10:
    compose: CentOS-Stream-10

    x86_64:
      image: CentOS Stream 10 x86_64 20250825
    aarch64:
      image: CentOS Stream 10 aarch64 20250825

  centos_stream_10_image_mode:
    compose: CentOS-Stream-10-image-mode

    x86_64:
      image: CentOS-Stream-10-image-mode-x86_64
