---
composes:

  fedora_38:
    compose: Fedora-38

    x86_64:
      image: Fedora-Cloud-Base-38-20240429.0.x86_64-hvm-us-east-2-gp3-0
    aarch64:
      image: Fedora-Cloud-Base-38-20240429.0.aarch64-hvm-us-east-2-gp3-0

  fedora_39:
    compose: Fedora-39

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-39-20241024.0
    aarch64:
      image: Fedora-Cloud-Base-39-20240805.0.aarch64

  fedora_40:
    compose: Fedora-40

    x86_64: &fedora_latest_ref_x86_64
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-40-20241024.0
    aarch64: &fedora_latest_ref_aarch64
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-40-20241024.0

  fedora_41:
    compose: Fedora-41

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-41-20240818.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-41-Prerelease-20241017.1

  # TFT-1221
  fedora_latest:
    compose: Fedora-latest

    x86_64: *fedora_latest_ref_x86_64
    aarch64: *fedora_latest_ref_aarch64

  fedora_rawhide:
    compose: Fedora-Rawhide

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-Rawhide-20241024.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-Rawhide-20241024.0

  centos_7:
    compose: CentOS-7

    x86_64:
      image: CentOS Linux 7 x86_64 - 2211
    aarch64:
      image: CentOS Linux 7 aarch64 - 2211

  centos_stream_8:
    compose: CentOS-Stream-8

    x86_64:
      image: CentOS Stream 8 x86_64 20240603
    aarch64:
      image: CentOS Stream 8 aarch64 20240603

  centos_stream_9:
    compose: CentOS-Stream-9

    x86_64:
      image: CentOS Stream 9 x86_64 20241021
    aarch64:
      image: CentOS Stream 9 aarch64 20241016

  centos_stream_10:
    compose: CentOS-Stream-10

    x86_64:
      image: CentOS Stream 10 x86_64 20241022
    aarch64:
      image: CentOS Stream 10 aarch64 20241022
