---
composes:

  fedora_39:
    compose: Fedora-39

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-39-20241031.0
    aarch64:
      image: Fedora-Cloud-Base-39-20240805.0.aarch64

  fedora_40:
    compose: Fedora-40

    x86_64: &fedora_latest_ref_x86_64
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-40-20241101.0
    aarch64: &fedora_latest_ref_aarch64
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-40-20241101.0

  fedora_41:
    compose: Fedora-41

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-41-Prerelease-20241025.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-41-Prerelease-20241017.1

  # TFT-1221
  fedora_latest:
    compose: Fedora-latest

    x86_64: *fedora_latest_ref_x86_64
    aarch64: *fedora_latest_ref_aarch64

  fedora_rawhide:
    compose: Fedora-Rawhide

    x86_64:
      image: Fedora-Cloud-Base-AmazonEC2.x86_64-Rawhide-20241101.0
    aarch64:
      image: Fedora-Cloud-Base-AmazonEC2.aarch64-Rawhide-20241101.0

  centos_7:
    compose: CentOS-7

    x86_64:
      image: CentOS Linux 7 x86_64 - 2211
    aarch64:
      image: CentOS Linux 7 aarch64 - 2211

  centos_stream_8:
    compose: CentOS-Stream-8

    x86_64:
      image: CentOS Stream 8 x86_64
    aarch64:
      image: CentOS Stream 8 aarch64

  centos_stream_9:
    compose: CentOS-Stream-9

    x86_64:
      image: CentOS Stream 9 x86_64 20241028
    aarch64:
      image: CentOS Stream 9 aarch64 20241028

  centos_stream_10:
    compose: CentOS-Stream-10

    x86_64:
      image: CentOS Stream 10 x86_64 20241029
    aarch64:
      image: CentOS Stream 10 aarch64 20241029
