---
#
# Testing Farm
#
all:
  children:
    #
    # Public Ranch
    #
    testing_farm_public:
      children:
        testing_farm_public_servers:
          hosts:
            # API, database, dispatcher
            testing_farm_public_server_01:
              ansible_host: ec2-52-14-131-2.us-east-2.compute.amazonaws.com

        # Hosts are managed via aws_ec2 inventory
        testing_farm_public_workers:

    #
    # Red Hat Ranch
    #
    testing_farm_redhat:
      children:
        testing_farm_redhat_servers:
          hosts:
            # API, database, dispatcher
            testing_farm_redhat_server_01:
              ansible_host: testing-farm-server-01.osci.redhat.com

        # Hosts are managed via aws_ec2 inventory
        testing_farm_redhat_workers:
