---
#
# For documentation see:
# https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html
#

plugin: amazon.aws.aws_ec2

cache: true
cache_plugin: ansible.builtin.jsonfile
cache_connection: .direnv/aws-cache

boto_profile: redhat_us_east_1_ansible_inventory

filters:
  tag:Name:
    - "testing_farm_worker_*"
    - "testing-farm-worker-*"
  instance-state-name: "running"

hostnames:
  - "tag:Name"

compose:
  ansible_host: private_ip_address

groups:
  testing_farm_redhat_workers: true
