---
composes:

  fedora_37:
    compose: Fedora-37

    x86_64:
      image: Fedora-Cloud-Base-37-20230615.0.x86_64-hvm-us-east-2-gp3-0
    aarch64:
      image: Fedora-Cloud-Base-37-20230926.0.aarch64-hvm-us-east-2-gp3-0

  fedora_38:
    compose: Fedora-38

    x86_64:
      image: Fedora-Cloud-Base-38-20240206.0.x86_64-hvm-us-east-2-gp3-0
    aarch64:
      image: Fedora-Cloud-Base-38-20240206.0.aarch64-hvm-us-east-2-gp3-0

  fedora_39:
    compose: Fedora-39

    x86_64: &fedora_latest_ref_x86_64
      image: Fedora-Cloud-Base-39-20240207.0.x86_64-hvm-us-east-2-gp3-0
    aarch64: &fedora_latest_ref_aarch64
      image: Fedora-Cloud-Base-39-20240207.0.aarch64-hvm-us-east-2-gp3-0

  # TFT-1221
  fedora_latest:
    compose: Fedora-latest

    x86_64: *fedora_latest_ref_x86_64
    aarch64: *fedora_latest_ref_aarch64

  fedora_rawhide:
    compose: Fedora-Rawhide

    x86_64:
      image: Fedora-Cloud-Base-Rawhide-20240207.n.0.x86_64-hvm-us-east-2-gp3-0
    aarch64:
      image: Fedora-Cloud-Base-Rawhide-20240207.n.0.aarch64-hvm-us-east-2-gp3-0

  centos_7:
    compose: CentOS-7

    x86_64:
      image: CentOS 7.9.2009 x86_64
    aarch64:
      image: CentOS 7.9.2009 aarch64

  centos_stream_8:
    compose: CentOS-Stream-8

    x86_64:
      image: CentOS Stream 8 x86_64 20240129
    aarch64:
      image: CentOS Stream 8 aarch64 20240129

  centos_stream_9:
    compose: CentOS-Stream-9

    x86_64:
      image: CentOS Stream 9 x86_64 20240129
    aarch64:
      image: CentOS Stream 9 aarch64 20240129
