---
- name: Generate job scripts
  become: true
  template:
    src: "{{ root_dir }}/ansible/templates/job-script.j2"
    dest: "/usr/local/bin/{{ job_name }}"
    mode: "a+rwx"
  loop: "{{ jobs_template_vars | dict2items }}"
  vars:
    job_vars: "{{ item.value }}"
    job_name: "{{ item.key | replace('_', '-') }}"
