---
- name: "Register {{ ansible_user }} user"
  user:
    name: "{{ ansible_user }}"
    state: present
  register: user_registered

- name: Make sure .ssh folder exits
  file:
    path: "{{ user_registered.home }}/.ssh"
    state: directory
    owner: "{{ user_registered.name }}"
    group: "{{ user_registered.name }}"
    mode: 0700

- name: Copy over shared ssh key
  copy:
    src: "{{ ssh_private_key }}"
    dest: "{{ user_registered.home }}/.ssh/id_rsa"
    owner: "{{ user_registered.name }}"
    group: "{{ user_registered.name }}"
    mode: 0600

- name: Copy over shared ssh public key
  copy:
    src: "{{ ssh_public_key }}.pub"
    dest: "{{ user_registered.home }}/.ssh/id_rsa.pub"
    owner: "{{ user_registered.name }}"
    group: "{{ user_registered.name }}"
    mode: 0600

- name: Make sure .ssh folder exits (root)
  become: true
  file:
    path: "/root/.ssh"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700

- name: Copy over shared ssh key (root)
  become: true
  copy:
    src: "{{ ssh_private_key }}"
    dest: "/root/.ssh/id_rsa"
    owner: "root"
    group: "root"
    mode: 0600
