---
- name: Write swapfile
  command: |
    dd if=/dev/zero of={{ swapfile_location }} bs=1M count={{ swapfile_size }} creates={{ swapfile_location }}
  register: write_swapfile
  when: swapfile_size

- name: Set swapfile permissions
  file: path={{ swapfile_location }} mode=600
  when: swapfile_size

- name: Create swapfile
  command: mkswap {{ swapfile_location }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  register: create_swapfile
  when: swapfile_size and write_swapfile.changed

- name: Enable swapfile
  command: swapon {{ swapfile_location }}
  environment:
    PATH: "{{ (ansible_env|default({})).PATH|default('') }}:/usr/local/sbin:/usr/sbin:/sbin"
  when: swapfile_size and create_swapfile.changed

- name: Add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ swapfile_location }}   none    swap    sw    0   0" state=present
  when: swapfile_size

- name: Configure vm.swappiness
  lineinfile: dest=/etc/sysctl.conf line="vm.swappiness = {{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present
  when: swapfile_swappiness

- name: Configure vm.vfs_cache_pressure
  lineinfile: dest=/etc/sysctl.conf line="vm.vfs_cache_pressure = {{ swapfile_vfs_cache_pressure }}" regexp="^vm.vfs_cache_pressure[\s]?=" state=present
  when: swapfile_vfs_cache_pressure

- name: Reload sysctl
  command: sysctl -p
