---
# aws --profile fedora ec2 describe-images --filter Name=name,Values=Fedora-Cloud-Base-32* | jq '.Images | .[] | .Name' | sort
- 'Fedora-32': 'Fedora-Cloud-Base-32-1.6.x86_64-hvm-us-east-2-gp2-0'
# aws --profile fedora ec2 describe-images --filter Name=name,Values=Fedora-Cloud-Base-33* | jq '.Images | .[] | .Name' | sort
- 'Fedora-33': 'Fedora-Cloud-Base-33-20210705.0.x86_64-hvm-us-east-2-gp2-0'
# aws --profile fedora ec2 describe-images --filter Name=name,Values=Fedora-Cloud-Base-34* | jq '.Images | .[] | .Name' | sort
- 'Fedora-34': 'Fedora-Cloud-Base-34-20210705.0.x86_64-hvm-us-east-2-gp2-0'
# aws --profile fedora ec2 describe-images --filter Name=name,Values=Fedora-Cloud-Base-Rawhide* | jq '.Images | .[] | .Name' | sort
- 'Fedora-Rawhide': 'Fedora-Cloud-Base-Rawhide-20210705.n.0.x86_64-hvm-us-east-2-gp2-0'
- 'CentOS-6': 'CentOS-6-x86_64-GenericCloud-1907'
- 'CentOS-7': 'CentOS 7.9.2009 x86_64'
- 'CentOS-8': 'CentOS 8.4.2105 x86_64'
- 'CentOS-Stream-8': 'CentOS Stream 8 x86_64'
- '^(.*)$': '\1'
