---

users:
  - name: artemis

ssh-keys:
  - name: master-key
    owner: artemis
    file: /configuration/master-key.yaml

priority-groups:
  - name: default-priority

pools:
  - name: aws-testing-farm-2c
    driver: aws
    parameters:
      command: aws
      master-key-name: testing-farm-worker

      # set default root disk size to 40GB
      default-root-disk-size: 40

      # availability zone match chosen subnet
      availability-zone: us-east-2c

      # seems 4k machines
      subnet-id: subnet-4f971734

      # security group for test environment
      security-group: sg-0f4c1a7c071bb9f59

      # instance details
      default-instance-type: t3.medium

      # wait timeout/tick for fulfilling spot request
      spot-request-timeout: 60
      spot-request-tick: 1

      # wait timeout/tick for instance becoming running
      instance-running-timeout: 120
      instance-running-tick: 1

      # tags to add to all created resources
      # tagging docs: https://mojo.redhat.com/docs/DOC-13812 https://mojo.redhat.com/docs/DOC-1030933
      tags:
        FedoraGroup: 'ci'
        ServiceName: 'Artemis'
        ServiceOwner: 'TFT'

      product-description:
        fedora: 'Linux/UNIX (Amazon VPC)'

      #additional-options:
      #  - "--no-associate-public-ip-address"
