---
#
# Testing Farm
#
all:
  children:
    #
    # Public Ranch
    #
    testing_farm_public_servers:
      hosts:
        # API, database, dispatcher
        testing_farm_public_server_01:
          ansible_host: ec2-52-14-131-2.us-east-2.compute.amazonaws.com

    testing_farm_public_workers:
      hosts:
        testing_farm_public_worker_01:
          ansible_host: ec2-3-129-244-87.us-east-2.compute.amazonaws.com
        testing_farm_public_worker_02:
          ansible_host: ec2-3-12-85-77.us-east-2.compute.amazonaws.com
        testing_farm_public_worker_03:
          ansible_host: ec2-3-137-140-191.us-east-2.compute.amazonaws.com
        testing_farm_public_worker_04:
          ansible_host: ec2-18-222-171-2.us-east-2.compute.amazonaws.com

    #
    # Red Hat Ranch
    #
    testing_farm_redhat_servers:
      hosts:
        # API, database, dispatcher
        testing_farm_redhat_server_01:
          ansible_host: testing-farm-server-01.osci.redhat.com

    testing_farm_redhat_workers:
      hosts:
        testing_farm_redhat_worker_01:
          ansible_host: ip-10-29-163-77.us-east-1.aws.redhat.com
